name: smart_fin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.2.3 <4.0.0"

dependencies:
    awesome_snackbar_content: ^0.1.3
    cupertino_icons: ^1.0.6
    fl_chart: ^0.67.0
    flutter:
        sdk: flutter
    flutter_svg: ^2.0.10+1
    gap: ^3.0.1
    http: ^1.2.0
    iconly: ^1.0.1
    image_cropper: ^6.0.0
    image_picker: ^1.0.8
    intl: ^0.18.1
    path: ^1.8.3
    permission_handler: ^11.3.1
    provider: ^6.1.2
    shared_preferences: ^2.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/images/avatars/
        - assets/icons/app/
        - assets/icons/categories/
        - assets/icons/default/light/
        - assets/icons/default/regular/
        - assets/icons/default/bold/
        - assets/fonts/
